GrassrootsFloodCtrl/GrassrootsFloodCtrl/Controllers/SuperviseController.cs
using GrassrootsFloodCtrl.Logic.Common;
using GrassrootsFloodCtrl.Model;
using GrassrootsFloodCtrl.Model.Enums;
using GrassrootsFloodCtrl.Model.Supervise;
using GrassrootsFloodCtrl.ServiceInterface;
using GrassrootsFloodCtrl.ServiceModel.Route;
using GrassrootsFloodCtrl.ServiceModel.Village;
using ServiceStack;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrassrootsFloodCtrl.Controllers
{
    [Authorize]
    public class SuperviseController : ControllerBase
    {
        #region 统计
        #region 省查看
        public ActionResult Index()
        {
            if ((RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.省级用户))
            {
                return View("Error", model: "登陆已到期，请重新登陆。");
            }
            ViewData["adcd"] = adcd;
            ViewData["rid"] = RoleID;
            //var r= HostContext.Resolve<SuperviseService>().Post(new SPersonLiable() { adcd=adcd });
            return View();
        }
        #endregion

        #region 市查看
        [HttpGet]
        [ValidateInput(false)]
        public ActionResult County(string id)
        {
            if ((RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.省级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.市级用户))
            {
                return View("Error", model: "登陆已到期，请重新登陆。");
            }
            ViewData["adcd"] = string.IsNullOrEmpty(id) ?adcd:id;
            ViewData["rid"] = RoleID;
            return View();
        }
        public ActionResult CountyInfo(string id)
        {
            if ((RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.省级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.市级用户))
            {
                return View("Error", model: "登陆已到期，请重新登陆。。");
            }
            if (string.IsNullOrEmpty(id)) throw new Exception("参数不能为空！");
            ViewData["adcd"] = string.IsNullOrEmpty(id) ? adcd : id;
            return View();
        }
        #endregion

        #region 县查看
        public ActionResult Towns(string id)
        {
            if ((RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.省级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.市级用户) && (RoleID !=(int)GrassrootsFloodCtrlEnums.RoleEnums.县级用户))
            {
                return View("Error", model: "登陆已到期，请重新登陆。");
            }
            var ac= string.IsNullOrEmpty(id) ? adcd : id;
            ViewData["adcd"] = ac;
            ViewData["cadcd"] = ac.Substring(0,4)+ "00000000000";
            ViewData["rid"] = RoleID;
            return View();
        }
        #endregion

        #region 镇级信息
        public ActionResult TownInfo(string id)
        {
            if ((RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.省级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.市级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.县级用户))
            {
                return View("Error", model: "登陆已到期，请重新登陆。");
            }
            var ac = string.IsNullOrEmpty(id) ? adcd : id;
            ViewData["adcd"] = ac;
            ViewData["ccadcd"] = ac.Substring(0, 4) + "00000000000";
            ViewData["cadcd"] = ac.Substring(0, 6) + "000000000";
            ViewData["rid"] = RoleID;
            return View();
        }
        public ActionResult TownVillage(string _adcd,string lng,string lat)
        {
            if ((RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.省级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.市级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.县级用户))
            {
                return View("Error", model: "登陆已到期，请重新登陆。。");
            }
            ViewData["adcd"] = _adcd;
            ViewData["lng"] = lng;
            ViewData["lat"] = lat;
            return View();
        }
        #endregion

        #region 县级统计
        public ActionResult tj()
        {
            if ((RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.省级用户))
            {
                return View("Error", model: "登陆已到期，请重新登陆。");
            }
            //var r= HostContext.Resolve<SuperviseService>().Post(new SPersonLiable() { adcd=adcd });
            return View();
        }
        #endregion
        #endregion
        #region 菜单
        public ActionResult left()
        {
            if (RoleID == null) { return View("Error", model: "登陆已到期，请重新登陆。"); }
            var url = "";
            var urlkh = "";
            var urlkhjl = "";
            var urllog = "";
            var urlapp = "";
            var urltask = "";
            var usrMessger = "";
            var userApp = "";
            switch (RoleID)
            {
                case 5:
                    url = "/Supervise";
                    urlkh = "/Supervise/CCKH";
                    urlkhjl = "/Supervise/CCHKJL";
                    urllog = "/Log/LogCityIndex";
                    urlapp = "/Supervise/AppInPostCityIndex";
                    usrMessger = "/Supervise/AppWarnList";
                    userApp = "/Supervise/AppUserList";
                    break;
                case 2:
                    url = "/Supervise/County";
                    urlkh = "/Supervise/CCKH";
                    urlkhjl = "/Supervise/CCHKJL";
                    urllog = "/Log/LogCountyIndex";
                    urlapp = "/Supervise/AppInPostCountyIndex";
                    usrMessger = "/Supervise/AppWarnList";
                    userApp = "/Supervise/AppUserList";
                    break;
                case 3:
                    url = "/Supervise/Towns";
                    urlkh = "";
                    urlkhjl = "";
                    urllog = "/Log/LogTownIndex";
                    urlapp = "/Supervise/AppInPostTownIndex";
                    urltask = "/TaskArragement/sendmessage";
                    usrMessger = "/Supervise/AppWarnList";
                    userApp = "/Supervise/AppUserList";
                    break;
                case 4:
                    url = "/Supervise/AppUserList";
                    break;
            }
            ViewData["url"] = url;
            ViewData["urlkh"] = urlkh;
            ViewData["urlkhjl"] = urlkhjl;
            ViewData["rid"] = RoleID;
            ViewData["urllog"] = urllog;
            ViewData["urlapp"] = urlapp;
            ViewData["urltask"] = urltask;
            ViewData["usrMessger"] = usrMessger;
            ViewData["userApp"] = userApp;
            return View();
        }
        #endregion
        #region 抽查
        /// <summary>
        /// 抽查考核
        /// </summary>
        /// <returns></returns>
        public ActionResult CCKH()
        {
            if ((RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.省级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.市级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.县级用户))
            {
                return View("Error", model: "登陆已到期，请重新登陆。");
            }
            ViewData["adcd"] = adcd;
            ViewData["rid"] = RoleID;
            ViewData["userid"] = UserId;
            ViewData["realname"] = UserSession.RealName;
            ViewData["checktime"] = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            try
            {
                ViewData["itemListCounty"] = GetList(5);
                ViewData["itemListTown"] = GetList(4);
                ViewData["itemListVillage"] = GetList(1);
            }
            catch (Exception ex) { }
            return View();
        }
        public List<SelectListItem> GetList(int tid)
        {
            using (var service = HostContext.ResolveService<PostService>())
            {
                var itemListCounty = new List<SelectListItem>();
                service.Get(new GetPostList()
                {
                    PageSize = int.MaxValue,
                    typeId = tid
                }).rows.ForEach(x =>
                {
                    itemListCounty.Add(new SelectListItem() { Text = x.PostName, Value = x.ID.ToString() });

                });
                return itemListCounty;
            }
        }
        /// <summary>
        /// 抽查记录
        /// </summary>
        /// <returns></returns>
        public ActionResult CCHKJL()
        {
            if ((RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.省级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.市级用户) && (RoleID != (int)GrassrootsFloodCtrlEnums.RoleEnums.县级用户))
            {
                return View("Error", model: "登陆已到期，请重新登陆。");
            }
            ViewData["adcd"] = adcd;
            ViewData["rid"] = RoleID;
            return View();
        }

        #endregion
        #region 到港统计
        public ActionResult AppInPostCityIndex()
        {
            //ViewData["s"] = DateTime.Now.AddMonths(-1).ToString("yyyy-MM-dd");
            // ViewData["e"] = DateTime.Now.ToString("yyyy-MM-dd");
            return View();
        }
        public ActionResult AppInPostCountyIndex(int? id, string s, string e,string _adcd, string grade)
        {
            ViewData["s"] = s;
            ViewData["e"] = e;
            ViewData["rid"] = RoleID;
            ViewData["adcd"] = string.IsNullOrEmpty(_adcd) && RoleID == 2 ? adcd : _adcd;
            ViewData["id"] = id == null ? 0:id;
            ViewData["grade"] = grade;
            return View();
        }
        public ActionResult AppInPostTownIndex(int? id, int? pid, string s, string e, string _adcd, string grade)
        {
            var _adcd1 = string.IsNullOrEmpty(_adcd) && RoleID == 3 ? adcd : _adcd;
            ViewData["s"] = s;
            ViewData["e"] = e;
            ViewData["adcd"] = _adcd1;
            ViewData["id"] = id;
            ViewData["pid"] = pid;
            ViewData["grade"] = grade;
            ViewData["adcdparent"] = _adcd1.Substring(0, 4) + "00000000000";
            ViewData["rid"] = RoleID;
            return View();
        }
        public ActionResult AppInPostTownInfo(string _adcd,int? id,int? pid)
        {

GrassrootsFloodCtrl/GrassrootsFloodCtrl/Controllers/TaskArragementController.cs
using GrassrootsFloodCtrl.Logic.AppApi;
using GrassrootsFloodCtrl.Model.Enums;
using GrassrootsFloodCtrl.ServiceModel.Route;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrassrootsFloodCtrl.Controllers
{
    public class TaskArragementController : ControllerBase
    {

        public IAppApiManager AppApiManager { get; set; }

        public ActionResult left()
        {
            if (RoleID == null) { return View("Error", model: "登陆已到期，请重新登陆。"); }
            var url = "";
            var urlkh = "";
            var urlkhjl = "";
            var urllog = "";
            var urlapp = "";
            var urltask = "";
            switch (RoleID)
            {
                case 5:
                    url = "/Supervise";
                    urlkh = "/Supervise/CCKH";
                    urlkhjl = "/Supervise/CCHKJL";
                    urllog = "/Log/LogCityIndex";
                    urlapp = "/Supervise/AppInPostCityIndex";
                    break;
                case 2:
                    url = "/Supervise/County";
                    urlkh = "/Supervise/CCKH";
                    urlkhjl = "/Supervise/CCHKJL";
                    urllog = "/Log/LogCountyIndex";
                    urlapp = "/Supervise/AppInPostCountyIndex";
                    break;
                case 3:
                    url = "/Supervise/Towns";
                    urlkh = "";
                    urlkhjl = "";
                    urllog = "/Log/LogTownIndex";
                    urlapp = "/Supervise/AppInPostTownIndex";
                    urltask = "/TaskArragement/sendmessage";
                    break;
            }
            ViewData["url"] = url;
            ViewData["urlkh"] = urlkh;
            ViewData["urlkhjl"] = urlkhjl;
            ViewData["rid"] = RoleID;
            ViewData["urllog"] = urllog;
            ViewData["urlapp"] = urlapp;
            ViewData["urltask"] = urltask;
            return View();
        }

        // GET: TaskArragement
        //public ActionResult Index()
        //{
        //    return View();
        //}
        /// <summary>
        /// 消息发送
        /// </summary>
        /// <returns></returns>
        public ActionResult TaskIndex()
        {
            //var newid = "331081000000000";
            //ViewData["s"] = DateTime.Now.AddMonths(-1).ToString("yyyy-MM-dd");
            //ViewData["e"] = DateTime.Now.ToString("yyyy-MM-dd");
            //ViewData["adcd"] = newid;
            //ViewData["adcdparent"] = newid.Substring(0, 4) + "00000000000";
            //ViewData["rid"] = RoleID;
            //return View();
            ViewData["adcd"] = adcd;
            ViewData["year"] = 2017;
            //ViewData["adcd"] = "331081000000000";
            ViewData["rid"] = RoleID;
            ViewData["startTime"] = DateTime.Now.AddDays(-7).ToString("yyyy-MM-dd");
            ViewData["endTime"] = DateTime.Now.AddDays(1).ToString("yyyy-MM-dd");
            return View();
        }
        public ActionResult FloatMenu()
        {
            ViewData["rid"] = RoleID;
            return View();
        }
        /// <summary>
        /// 履职查看
        /// </summary>
        /// <returns></returns>
        public ActionResult WorkState()
        {
            ViewData["year"] = 2017;
            ViewData["adcd"] = adcd;
            ViewData["rid"] = 3;
            ViewData["startTime"] = DateTime.Now.AddDays(-7).ToString("yyyy-MM-dd");
            ViewData["endTime"] = DateTime.Now.AddDays(1).ToString("yyyy-MM-dd");
            return View();
        }
        /// <summary>
        /// 消息发送
        /// </summary>
        /// <returns></returns>
        public ActionResult SendMessage()
        {
            ViewBag.Title = "发送消息";
            var evevtModel = new RouteGetAppWarnSelect();
            evevtModel.adcd = adcd;
            var evnetList = AppApiManager.GetWarnSelectList(evevtModel);
            var itemList = new List<SelectListItem>();
            foreach (var item in evnetList.WarnList)
            {
                itemList.Add(new SelectListItem() { Text = item.EventName, Value =item.Id.ToString() });
            }

            ViewData["itemList"] = itemList;
            ViewData["adcd"] = adcd;
            ViewBag.adcd = adcd;
            ViewBag.username = Session["username"];
            return View();
        }

        public ActionResult AddSendMessage()
        {
            string evnetId = Request.Form["EventId"].ToString();
            string leverId = Request.Form["LevelId"].ToString();
            string sendContent = Request.Form["SendContent"].ToString();
            string remark = Request.Form["Remark"].ToString();
            var model = new RouteAppWarnInfo();
            model.adcd = adcd;
            model.AppWarnEventId = int.Parse(evnetId);
            model.Remark = remark;
            model.userName = UserName;
            model.WarnLevel = int.Parse(leverId);
            model.WarnMessage = sendContent;
            var json = AppApiManager.AddAppWarnInfoAndAppSendMessage(model);
            return Json(json,JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 事件追踪
        /// </summary>
        /// <returns></returns>
        public ActionResult EventTrail()
        {
            ViewData["year"] = 2017;
            ViewData["adcd"] = "331081000000000";
            ViewData["rid"] = 3;
            ViewData["startTime"] = DateTime.Now.AddMonths(-1).ToString("yyyy-MM-dd");
            ViewData["endTime"] = DateTime.Now.ToString("yyyy-MM-dd");
            return View();
        }

        public ActionResult AddEvnet()
        {
            string eventName = Request.Form["EventName"].ToString();
            var model = new RouteAddAppWarnEvent();
            model.userName = UserName;
            model.EventName = eventName;
            var resurlt = AppApiManager.AddAppWarnEvent(model);
            return Json(resurlt,JsonRequestBehavior.AllowGet);
        }

        public ActionResult ReceivePersonDetail(string appWarnInfoID)
        {
            this.ViewData["appInfoID"] = appWarnInfoID;
            this.ViewData["rid"] = this.RoleID;
            return View();
        }

        public ActionResult guiji(string receiveUserName)
        {
            this.ViewBag.userName2 = receiveUserName;
            return View();
        }
        public ActionResult lvzhi(string resevusername, string xiaoshijian,string dashijian)
        {
            ViewBag.resevusername = resevusername;
            ViewBag.xiaoshijian = xiaoshijian;
            ViewBag.dashijian = dashijian;
            return View();
        }
        
        public ActionResult GpsDisplay()
        {
            return this.View();
        }

        public ActionResult Emergency()
        {
            ViewBag.roleid = RoleID;
            ViewBag.username = UserName;
            ViewBag.adcd = adcd;
            return this.View();
        }

        public ActionResult SendMessageList()
        {
            return this.View();
        }

        public ActionResult VilliageDuty(string resiveadcd, int warninfoid)
        {
            ViewBag.resiveadcd = resiveadcd;
            ViewBag.warninfoid = warninfoid;
            return View();
        }

        //public ActionResult RegCount()
        //{
        //    return View();
        //}

    }
}

GrassrootsFloodCtrl/GrassrootsFloodCtrl/Views/Shared/_App.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    .mm {
        height: 100%;
    }
    #rowslist {
        padding-left: 30px;
        overflow-x: hidden;
        overflow-y: scroll;
    }
    .jdkh-list {
        cursor: pointer;
    }
</style>
@RenderSection("style", required: false)
<link href="~/Content/Supervise/css/style.css" type="text/css" rel="stylesheet" />
<div class="main">
    @Html.Action("left","TaskArragement")
    <div class="main-newright">
        @RenderBody()
    </div>
</div>
@RenderSection("scripts", required: false)

GrassrootsFloodCtrl/GrassrootsFloodCtrl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="~/favicon.ico">
    <title>浙江省基层防汛防台体系信息管理系统</title>
    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")
    <!-- View specific styles -->
    @RenderSection("styles", required: false)
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/scripts/others/respond.min.js")"></script>
    <![endif]-->
    @Scripts.Render("~/Bundles/vendor/js/top")
    <script>
        //前提：所有ajax请求都是用jquery的$.ajax发起的，而非原生的XHR；
        var ajaxBack = $.ajax;
        var ajaxCount = 0;
        var ajaxTimeid = 0;
        var allAjaxDone = function () {
            try {
                $('#loadingDiv').fadeOut();

                if (map) {
                    map.invalidateSize();
                };
            } catch (e) {
            }
        } //一行代码，就可以知道所有ajax请求什么时候结束
        //由于get/post/getJSON等，最后还是调用到ajax，因此只要改ajax函数即可
        var ajaxManager = [];
        $.ajax = function(setting) {
            ajaxCount++;
            var cb = setting.complete;
            setting.complete = function() {
                if ($.isFunction(cb)) {
                    cb.apply(setting.context, arguments);
                }
                ajaxCount--;
                if (ajaxCount == 0 && $.isFunction(allAjaxDone)) {
                    clearTimeout(ajaxTimeid);
                    allAjaxDone();
                }
            }
            return ajaxBack(setting);
        }
        ajaxTimeid = setTimeout(function() {
            if (ajaxCount == 0) {
                allAjaxDone();
            }
        }, 200);

        $(function () {
            var h = $(window).height();
            $("#main div[class='mm']").height(h);
        });
    </script>

    <style type="text/css">
        .mm {
            height: 530px;
            height: -moz-calc(100% - 40px);
            height: -webkit-calc(100% - 40px);
            height: calc(100% - 40px);
            overflow: hidden;
            overflow-y: auto;
        }

        #loadingDiv {
            position: fixed;
            top: 60px;
            width: 100%;
            height: 530px;
            height: -moz-calc(100% - 40px);
            height: -webkit-calc(100% - 40px);
            height: calc(100% - 40px);
            background: #fff;
            z-index: 9999;
        }

        .adddtable_ts {
            color: #ff0000;
        }
        * {
            margin: 0;
            padding: 0;
            list-style-type: none;
        }

        a, img {
            border: 0;
        }

        body {
            font: 12px/180% Arial, Helvetica, sans-serif, "新宋体";
            background: #ddd;
        }

        /* leftsead */
        #leftsead {
            width: 131px;
            height: 143px;
            position: fixed;
            top: 258px;
            right: 0px;
        }

        *html #leftsead {
            margin-top: 258px;
            position: absolute;
            top: expression(eval(document.documentElement.scrollTop));
        }

            #leftsead li {
                width: 131px;
                height: 55px;
            }

                #leftsead li img {
                    float: right;
                }

                #leftsead li a {
                    height: 49px;
                    float: right;
                    display: block;
                    min-width: 47px;
                    max-width: 131px;
                }

                    #leftsead li a .shows {
                        display: block;
                    }

                    #leftsead li a .hides {
                        margin-right: -143px;
                        cursor: pointer;
                        cursor: hand;
                    }

                    #leftsead li a.youhui .hides {
                        display: none;
                        position: absolute;
                        right: 190px;
                        top: 2px;
                    }
    </style>

    <!--浮动窗文件开始-->
    <link href="~/Content/floatmenu/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/floatmenu/css/normalize.css" rel="stylesheet" />
    <link href="~/Content/floatmenu/css/zzsc-demo.css" rel="stylesheet" />
    <link href="~/Content/floatmenu/css/dice-menu.min.css" rel="stylesheet" />
    <!--浮动窗文件结束-->
</head>
<body>

    <div id="wrapper">
        @Html.Partial("_TopBar")
        <div id="main">
            <div class="mm" style="z-index: -1">
                @RenderBody()
            </div>
            <div id="loadingDiv">
                <img src="~/images/loading.gif" style="position: absolute; top: 200px; left: 50%;  margin-left: -110px;" />
            </div>
        </div>
    </div>

 <div id="modalBox" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-lg" style="width: 960px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" id="hideClose" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalTitle"></h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal" id="btnModalClose">关闭</a>
                <a href="#" class="btn btn-primary" id="btnModalSave">确定</a>
            </div>
        </div>
    </div>
</div>
    @*<ul class="dice-menu">
        <li style="background-color:#2c77ec"><span  class ="fa fa-circle-o-notch"></span></li>
        <li style="background-color:#2c77ec"><span class="fa fa-envelope"><a  href="/TaskArragement/TaskIndex"></a></span></li>
        <li style="background-color:#2c77ec"><span class="fa fa-qq"><a href="/TaskArragement/TaskIndex"></a></span></li>     
    </ul>*@
    
    @*@Html.Action("FloatMenu", "TaskArragement")*@
    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")
    @RenderSection("scripts", required: false)
    <script src="~/js/plugins/layer/layer.js"></script>

    @*<script src="~/Content/floatmenu/js/jquery-1.11.0.min.js"></script>*@
    <script src="~/Content/floatmenu/js/jquery.easing.min.js"></script>
    <script src="~/Content/floatmenu/js/dice-menu.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            $("#leftsead a").hover(function () {
                if ($(this).prop("className") == "youhui") {
                    $(this).children("img.hides").show();
                } else {
                    $(this).children("img.hides").show();
                    $(this).children("img.shows").hide();
                    $(this).children("img.hides").animate({ marginRight: '0px' }, 'slow');
                }
            }, function () {
                if ($(this).prop("className") == "youhui") {
                    $(this).children("img.hides").hide('slow');
                } else {
                    $(this).children("img.hides").animate({ marginRight: '-143px' }, 'slow', function () { $(this).hide(); $(this).next("img.shows").show(); });
                }
            });

            $("#top_btn").click(function () { if (scroll == "off") return; $("html,body").animate({ scrollTop: 0 }, 600); });

        });
    </script>
</body>
</html>

GrassrootsFloodCtrl/GrassrootsFloodCtrl/Views/Shared/_StaticsAnalysisLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    .mm {
        height: 100%;
    }

    #rowslist {
        padding-left: 30px;
        overflow-x: hidden;
        overflow-y: scroll;
    }

    .jdkh-list {
        cursor: pointer;
    }
</style>
<link href="~/Content/Supervise/css/style.css" type="text/css" rel="stylesheet" />
<div class="main">
    @Html.Action("left", "StatisAnalysis")
    <div class="main-newright">
        <br />
        @RenderBody()
    </div>
</div>

GrassrootsFloodCtrl/GrassrootsFloodCtrl/Views/Shared/_SuperviseLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    .mm {
        height: 100%;
    }
    #rowslist {
        padding-left: 30px;
        overflow-x: hidden;
        overflow-y: scroll;
    }
    .jdkh-list {
        cursor: pointer;
    }
</style>
<link href="~/Content/Supervise/css/style.css" type="text/css" rel="stylesheet" />
<link href="/css/plugins/bootstrap-table/bootstrap-table.min.css"
      rel="stylesheet">
<link href="/css/plugins/jsTree/style.min.css" rel="stylesheet">
<link href="/css/plugins/jqTreeGrid/jquery.treegrid.css"
      rel="stylesheet">
<link href="/css/plugins/summernote/summernote-0.8.8.css"
      rel="stylesheet">
<link href="/css/animate.css"
      rel="stylesheet">
<link href="/css/plugins/chosen/chosen.css" rel="stylesheet">
<link href="/css/style.css?v=4.1.0"
      rel="stylesheet">
<div class="main">
    @Html.Action("left", "Supervise")
    <div class="main-newright">
        @RenderBody()
    </div>
</div>
@RenderSection("scripts", required: false)